application: mealsloth-freya-ap01
version: 1
runtime: python27
api_version: 1
threadsafe: true

env_variables:
  DJANGO_SETTINGS_MODULE: 'Freya.settings'

handlers:
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico
- url: /static
  static_dir: static
  application_readable: true
- url: /.*
  script: main.app

libraries:
- name: django
  version: "1.5"
- name: MySQLdb
  version: "1.2.5"